# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alex Craver - Russian Environmental History
tagline:          'PhD Candidate in History'
description:      'Personal Homepage'
url:              https:ahcraver.github.io
baseurl:          /

plugins:
  - jekyll-paginate
  - jekyll-gist
